export const technoligies = {
  TypeScript: {
    color: "007ACC",
    logo: "typescript",
    logoColor: "white",
    link: "https://www.typescriptlang.org/",
  },
  JavaScript: {
    color: "F7DF1E",
    logo: "javascript",
    logoColor: "black",
    link: "https://www.javascript.com/",
  },
  Rust: {
    color: "000000",
    logo: "rust",
    logoColor: "orange",
    link: "https://www.rust-lang.org/",
  },
  "Node.js": {
    color: "43853D",
    logo: "node.js",
    logoColor: "white",
    link: "https://nodejs.org/",
  },
  "Express.js": {
    color: "404d59",
    logo: "express",
    logoColor: "61DAFB",
    link: "https://expressjs.com/",
  },
  "Office.js": {
    color: "2D8CFF",
    logo: "microsoft-office",
    logoColor: "white",
    link: "https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-yo",
  },
  React: {
    color: "20232A",
    logo: "react",
    logoColor: "61DAFB",
    link: "https://reactjs.org/",
  },
  "Next.js": {
    color: "000000",
    logo: "next.js",
    logoColor: "white",
    link: "https://nextjs.org/",
  },
  Drizzle: {
    color: "C5F74F",
    logo: "drizzle",
    logoColor: "000",
    link: "https://orm.drizzle.team/",
  },
  PostgreSQL: {
    color: "316192",
    logo: "postgresql",
    logoColor: "white",
    link: "https://www.postgresql.org/",
  },
  MySQL: {
    color: "4479A1",
    logo: "mysql",
    logoColor: "fff",
    link: "https://www.mysql.com/",
  },
  "GitHub Actions": {
    color: "2088FF",
    logo: "github-actions",
    logoColor: "white",
    link: "https://github.com/features/actions",
  },
  OpenTelemetry: {
    color: "FFFFFF",
    logo: "opentelemetry",
    logoColor: "black",
    link: "https://opentelemetry.io/",
  },
  Prometheus: {
    color: "E6522C",
    logo: "prometheus",
    logoColor: "white",
    link: "https://prometheus.io/",
  },
  Grafana: {
    color: "F46800",
    logo: "grafana",
    logoColor: "white",
    link: "https://grafana.com/",
  },
  Playwright: {
    color: "2EAD33",
    logo: "playwright",
    logoColor: "white",
    link: "https://playwright.dev/",
  },
  Jest: {
    color: "C21325",
    logo: "jest",
    logoColor: "white",
    link: "https://jestjs.io/",
  },
  Bootstrap: {
    color: "563D7C",
    logo: "bootstrap",
    logoColor: "white",
    link: "https://getbootstrap.com/",
  },
};
